trigger:
- master
pr:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/.azure-pipeline/gitdiff.ps1'
    arguments: '$(Build.SourceVersion)'    
- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/.azure-pipeline/ymlparser.ps1'
    arguments: $(System.DefaultWorkingDirectory) $(yamlFileName)
- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/.azure-pipeline/accounttypeselector.ps1'
    arguments: $(cloud)    
- task: AzurePowerShell@4
  displayName: 'Check Resource Name Availability in local instance'
  inputs: 
    connectedServiceNameARM: $(connectedServiceNameARM)
    scriptType: filePath
    scriptArguments:
      -Type $(cloud) -AccountName $(accountName)
    scriptPath: '$(ServiceRootPath)/CheckResourceNameAvailability.ps1'
    azurePowershellVersion: latestVersion